content: add context sample for vue3
matschik/component-party pull request #151
Opened 2023-02-07 05:02 UTC by ismailassa

The context sample for vue3 was missing. Here you have one using the the Provide / Inject mechanism:
https://vuejs.org/guide/components/provide-inject.html#provide-inject

2023-02-09 00:16 UTC, matschik requested changes

2023-02-09 00:16 UTC, matschik commented on content/4-component-composition/5-context/vue3/App.vue
> +provide("userContextProvider", { user, updateUsername });
To match Svelte example, use context name `user` rather than `userContextProvider`.

2023-02-09 00:16 UTC, matschik commented on content/4-component-composition/5-context/vue3/UserProfile.vue
> +const { user, updateUsername } = inject("userContextProvider");
To match Svelte example, use context name `user` rather than `userContextProvider`.

2023-02-09 00:16 UTC, matschik commented on content/4-component-composition/5-context/vue3/UserProfile.vue
> +    <button @click="updateUsername('Jane')">
You are calling the function directly, that's wrong. It must be a function declaration, not a function call.

2023-02-09 04:24 UTC, ismailassa reviewed
Thanks for the feedback!

2023-02-10 11:11 UTC, merged

2023-02-10 11:11 UTC, matschik commented
Tested using Vue3 playground: https://sfc.vuejs.org/#eNqFUk1v2zAM/SuELk2A1EKDnTzH6A67DBiwS7GLLo5Cr0ptSdBHtiHwfx8l2VmaffRGkU/vkY88sw/WVqeIrGaNl07ZAB5DtK3QarTGBTiDw34D1pmTOiBM0DszgmD0SbD3F9iTR/fFmV4NuCAqfpVMIhkvjfYBIlVgl6hXZ6EB1KGGh02KUkV3I9bEELWSxul3W8FyDcdODa8Kj/ijGy3RSzNm0LQmjT5qGZTREO2hC5jaSJSrhXsNWTQ9q1M3RKyWCvW0hMQzCT3PvSJNypMEGZKizQ03ZOGGFxPJPnoEpNYIQy+A5vmh/YoD9Ymw7+QLERWm39rT1HBCZfS1n5xSDb+wsQ0rpt+Pna2O3mjaXh5IzAUvWF1GTLnsfHLtOQTra859L9M6jr4y7hunqHJRBzVihX683zvzPbV1JJZEQSZMJHmzy/8djNJHlOHPUymr/5d/ZH35ePH6LUcP6pSDZO62/fwT5v7Ixe1SsO2iQI78zfDU+Yz8WM5rgeVre43ZxxDorB7loOTLTrDVGnbt7ZXdfeo03q0Fm38BPGXA5bIgGEiYmZQX1jITL0Ndr3v6BYkyQYs=